// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0eZZcyKtRA_FYPAE8rYhGBK8OrOOIS_o',
    appId: '1:425270527605:web:50f199e20c24240f501a3c',
    messagingSenderId: '425270527605',
    projectId: 'todoapp-f0e98',
    authDomain: 'todoapp-f0e98.firebaseapp.com',
    storageBucket: 'todoapp-f0e98.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs0Gp3E0FDw20Q8wNanDAbB7BejSy6alE',
    appId: '1:425270527605:android:12ff55c3bdaafbc8501a3c',
    messagingSenderId: '425270527605',
    projectId: 'todoapp-f0e98',
    storageBucket: 'todoapp-f0e98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYnYDxB-AGhFZ-qf_Urrz0MV3BmyxLiCU',
    appId: '1:425270527605:ios:e84d9d99f730fc52501a3c',
    messagingSenderId: '425270527605',
    projectId: 'todoapp-f0e98',
    storageBucket: 'todoapp-f0e98.appspot.com',
    iosClientId: '425270527605-ambja9q63i25s96p95o1mlpskr25gf8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYnYDxB-AGhFZ-qf_Urrz0MV3BmyxLiCU',
    appId: '1:425270527605:ios:e84d9d99f730fc52501a3c',
    messagingSenderId: '425270527605',
    projectId: 'todoapp-f0e98',
    storageBucket: 'todoapp-f0e98.appspot.com',
    iosClientId: '425270527605-ambja9q63i25s96p95o1mlpskr25gf8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
